# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b5d8cfc3ff0fd9950993eab46e928526a521050d25bc74b04fec8881480ec3a12373149bd244ea1fc5bdb886693d4bcc6e9665f1e760bea091113085778b4b6

test:
  secret_key_base: d4993ce3023b0c65daab4bfc58cdd6847e91cc223ece5fdfa832547f2762457be551ce04577aa561a437e36cd6d9d93e4c2fe7d6140c51bf006dacd8a014861e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
